server:
  port: 8080

spring:
  application:
    name: book

  profiles:
    active: prod

  datasource:
    username: testdemo
    password: testdemo@123
    url: jdbc:postgresql://localhost:5432/db_test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

  config:
    import: optional:configserver:http://localhost:8071/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      bookBorrowDetailSupport:
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 3000
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      bookBorrowDetailRetry:
        max-attempts: 3
        wait-duration: 2000
  ratelimiter:
    configs:
      default:
        register-health-indicator: true
    instances:
      bookBorrowDetailRateLimit:
        timeout-duration: 5000
        limit-refresh-period: 10000
        limit-for-period: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: book-service
    description: provide book service
    version: 1.0.0

logging:
  level:
    com.vicheak.book.bookservice: DEBUG