version: "3.8"

services:
  pg-admin:
    image: dpage/pgadmin4:6
    container_name: book_service_pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin@123
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    networks:
      - book_network

  book_service_db:
    image: postgres:14-alpine
    container_name: book_service_db
    environment:
      - POSTGRES_USER=book
      - POSTGRES_PASSWORD=book@123
      - POSTGRES_DB=book_db
    ports:
      - "5438:5432"
    networks:
      - book_network
    
  configserver:
    image: vicheak/book_configserver:latest
    container_name: book_configserver
    ports:
      - "8071:8071"
    networks:
      - book_network

  book_service: 
    image: vicheak/book_service:latest
    container_name: book_service 
    ports:
      - "8080:8080"
    networks:
      - book_network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  book_network: